name: manual-renovate-bot-trigger

on:
  workflow_dispatch:

jobs:
  manual-renovate-call:
    uses: simatic-ax/renovate-config/.github/workflows/reusable-renovate-workflow.yml@main
    secrets: inherit
    with:
        renovate_repository_filter: "simatic-ax/*"
