name: automatic-renovate-bot-trigger

on:
  workflow_call:
    inputs:
      renovate_repository_filter:
        description: 
          "This fills the setting autodiscoverFilter of renovate. The name of the repository from which the job was called should be written here, according to the scheme 'simatic-ax/repository_name'"
        required: true
        type: string

jobs:
  renovate:
    runs-on: ubuntu-24.04
    container: 
        image: ghcr.io/renovatebot/renovate:39.185.9
        options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref: ${{ github.ref }}
            
      - name: set_variables
        shell: bash
        env:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}
          RENOVATE_REPOSITORY_FILTER: ${{ inputs.renovate_repository_filter }}
        run: |
          curl -H "Authorization: Bearer $APAX_TOKEN" "https://api.simatic-ax.siemens.io/apax/login?format=npmrc" -o .npmrc
          # Store the npmrc file in the RENOVATE_NPMRC variable so that it can be used in the next step:
          {
            echo 'RENOVATE_NPMRC<<EOF'
            cat .npmrc
            echo EOF
          } >> "$GITHUB_ENV"
          # Store the value of '' in globale variable RENOVATE_AUTODISCOVERFILTER, that is used in renovate-global-config.js om next step:
          echo "RENOVATE_AUTODISCOVERFILTER=$RENOVATE_REPOSITORY_FILTER" >> "$GITHUB_ENV"
          
          # Mask the contents of the npmrc file so that they don't appear in job logs:
          if [ -f .npmrc ]; then
            while IFS= read -r line || [ -n "$line" ]; do
              if [ -n "$line" ] && [[ ! "$line" =~ ^# ]]; then
                echo "::add-mask::${line}"
              fi
            done < .npmrc
          else
            echo "Error: .npmrc file not found" >&2
            exit 1
          fi
      - name: install_apax
        run: |
          # Change to the project directory
          cd ${{ inputs.path }}

          echo "print ls"
          ls

          chmod +x /Global-Config/my-entrypoint.sh

      - name: Self-hosted Renovate
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: "Global-Config/renovate-global-config.js"
          LOG_LEVEL: "debug"
          # RENOVATE_CONFIG_MIGRATION: "true" # ensure all repositories receive config migration PRs
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          # GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
          # HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          # HUB_DOCKER_COM_TOKEN: ${{ secrets.HUB_DOCKER_COM_TOKEN }}
  


      #  uses: renovatebot/github-action@v41.0.14
      #  with:
      #    configurationFile: Global-Config/renovate-global-config.js
      #    docker-cmd-file: Global-Config/my-entrypoint.sh
      #    docker-user: root
      #    token: ${{ secrets.RENOVATE_TOKEN }}
      #  env:
      #      LOG_LEVEL: 'debug'
